Algoritmo "BoasVindas"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costa dos Santos
// Descrição    : Aqui você descreve o que o programa faz! (função)
// Autor(a)     : Josevan Oliveira de Albuquerque
// Data atual   : 06/04/2025
Var
// Seção de Declarações das variáveis 
 nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite seu nome:")
 leia(nome)
 escreval("Bem-vindo,",nome,"!")

Fimalgoritmo