Algoritmo "Numeros1a10"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson (Obama)
// Descrição    : Lê dois números e informa qual é o maior
// Autor(a)     : Josevan Oliveira De Albuquerque
// Data atual   : 15/04/2025

Var
// Seção de Declarações das variáveis
    i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    i<-1
    enquanto i <= 10 faca
        escreval(i,"")
        i <- i + 1
        fimenquanto

fimalgoritmo