Algoritmo "NumerosPares"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson (Obama)
// Descrição    : Lê dois números e informa qual é o maior
// Autor(a)     : Josevan Oliveira De Albuquerque
// Data atual   : 15/04/2025

Var
// Seção de Declarações das variáveis
    i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 2 ate 50 passo 2 faca
   escreval(i,"")
   fimpara
fimalgoritmo