Algoritmo "OlaMumdo"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costa dos Santos
// Descrição    : Aqui você descreve o que o programa faz! (função)
// Autor(a)     : Josevan Oliveira de Albuquerque
// Data atual   : 05/04/2025
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Olá, mundo!")

Fimalgoritmo                                                                z